AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Static website hosting for bryandeleon.com.
  S3 (private) + CloudFront OAC + ACM certificate + Route 53 records
  + GitHub Actions OIDC deploy role.
  Deploy this stack to us-east-1 (required for ACM + CloudFront).

# ─────────────────────────────────────────────────────────────────
# PARAMETERS
# ─────────────────────────────────────────────────────────────────
Parameters:
  DomainName:
    Type: String
    Default: bryandeleon.com
    Description: Apex domain name (no www prefix)

  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID for DomainName

  GitHubOrg:
    Type: String
    Description: GitHub username or org (e.g. bdeleon)

  GitHubRepo:
    Type: String
    Description: GitHub repository name (e.g. bryan-website)

  CreateGitHubOIDCProvider:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: >
      Set to false if a GitHub Actions OIDC provider already exists in
      this account (arn:aws:iam::<account>:oidc-provider/token.actions.githubusercontent.com).
      The deploy-stack.sh script detects this automatically.

# ─────────────────────────────────────────────────────────────────
# CONDITIONS
# ─────────────────────────────────────────────────────────────────
Conditions:
  ShouldCreateOIDCProvider: !Equals [!Ref CreateGitHubOIDCProvider, "true"]

# ─────────────────────────────────────────────────────────────────
# RESOURCES
# ─────────────────────────────────────────────────────────────────
Resources:

  # ── ACM Certificate ─────────────────────────────────────────────
  # CloudFormation auto-creates Route 53 validation records and waits
  # for validation before proceeding (~5-10 min on first deploy).
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "www.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub "www.${DomainName}"
          HostedZoneId: !Ref HostedZoneId

  # ── S3 Bucket ────────────────────────────────────────────────────
  # Private bucket — not a website host. CloudFront serves all traffic
  # via OAC. Account ID suffix ensures globally unique bucket name.
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ── S3 Bucket Policy ─────────────────────────────────────────────
  # Grants CloudFront OAC read access. The aws:SourceArn condition
  # scopes the grant to exactly this distribution (prevents confused
  # deputy attacks from other CloudFront distributions).
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontOAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${WebsiteBucket.Arn}/*"
            Condition:
              StringEquals:
                "aws:SourceArn": !Sub
                  - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistId}"
                  - DistId: !Ref Distribution

  # ── CloudFront Origin Access Control ────────────────────────────
  # OAC (replaces legacy OAI). Uses SigV4 signing for S3 REST access.
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${DomainName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # ── CloudFront Distribution ──────────────────────────────────────
  # ~15-20 min to propagate globally on first create.
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "${DomainName} website"
        HttpVersion: http2and3
        IPV6Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
          - !Sub "www.${DomainName}"
        PriceClass: PriceClass_100  # US, Canada, Europe

        Origins:
          - Id: S3Origin
            # Must use regional domain name (not global) for OAC
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
            # Required field when using OAC — must be empty string (not OAI)
            S3OriginConfig:
              OriginAccessIdentity: ""

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          # AWS managed CachingOptimized policy
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6

        # S3 private bucket returns 403 for missing keys (not 404).
        # Convert both to a 404 served from index.html.
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 10
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 10

        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  # ── Route 53 Records ─────────────────────────────────────────────
  # A + AAAA alias records for apex and www → CloudFront.
  # Z2FDTNDATAQYW2 is the fixed hosted zone ID for ALL CloudFront
  # distributions (AWS constant, not account-specific).
  DnsRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            DNSName: !GetAtt Distribution.DomainName
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2
        - Name: !Ref DomainName
          Type: AAAA
          AliasTarget:
            DNSName: !GetAtt Distribution.DomainName
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2
        - Name: !Sub "www.${DomainName}"
          Type: A
          AliasTarget:
            DNSName: !GetAtt Distribution.DomainName
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2
        - Name: !Sub "www.${DomainName}"
          Type: AAAA
          AliasTarget:
            DNSName: !GetAtt Distribution.DomainName
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2

  # ── GitHub Actions OIDC Provider ────────────────────────────────
  # Conditional — only created if no GitHub OIDC provider exists yet.
  # The deploy-stack.sh script detects this automatically.
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Condition: ShouldCreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd

  # ── GitHub Actions IAM Role ──────────────────────────────────────
  # Scoped to pushes to the main branch of the specific repo.
  # Uses !If to reference the provider whether or not this stack
  # created it (handles both CreateGitHubOIDCProvider values).
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${DomainName}-github-deploy"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !If
                - ShouldCreateOIDCProvider
                - !Ref GitHubOIDCProvider
                - !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": sts.amazonaws.com
              StringLike:
                "token.actions.githubusercontent.com:sub": !Sub "repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/main"
      Policies:
        - PolicyName: WebsiteDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: S3Sync
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt WebsiteBucket.Arn
                  - !Sub "${WebsiteBucket.Arn}/*"
              - Sid: CloudFrontInvalidate
                Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}"

# ─────────────────────────────────────────────────────────────────
# OUTPUTS
# ─────────────────────────────────────────────────────────────────
Outputs:
  S3BucketName:
    Description: S3 bucket name — set as S3_BUCKET GitHub secret
    Value: !Ref WebsiteBucket

  CloudFrontDistributionId:
    Description: CloudFront distribution ID — set as CLOUDFRONT_DISTRIBUTION_ID GitHub secret
    Value: !Ref Distribution

  DeployRoleArn:
    Description: IAM role ARN for GitHub Actions — set as AWS_DEPLOY_ROLE_ARN GitHub secret
    Value: !GetAtt GitHubActionsRole.Arn

  WebsiteURL:
    Description: Public website URL
    Value: !Sub "https://${DomainName}"
